name: test
on:
  push:
  schedule:
    - cron: '0 12 */3 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            whoami
            ls -a
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
#          key: ${{ secrets.PRIVATE_KEY}}
          pass: ${{ secrets.PASS }}
          args: "-tt -vvv"
