name: test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls -a
          host: ${{ secrets.HOST }}
          user: theking
#          key: ${{ secrets.PRIVATE_KEY}}
          pass: ${{ secrets.PASS }}
          args: "-tt -vvv"
