name: 自动部署

on:
  push:
    branches:
      - master
    # paths-ignore:
    #   - README.md
    #   - LICENSE
    corn
    paths:
      - src/**
      - package.json

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH 命令拉取代码
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}

          script: |
            cd /www/blog
            sudo git pull
            npm i
            npm run build
