name: 自动部署

on:
  push:
  schedule:
    - cron: '0 12 */3 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH 命令拉取代码
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.SSH_PASSWORD }}

          script: |
            whoami
            free -m
